language: node_js
node_js: lts/*
install: 
  - npm cache clean --force
  - rm -rf node_modules
  - npm install -g firebase-tools
  - npm install
script: 
  - echo "script"
  - npm run build

after_success:
  - firebase deploy --token $FIREBASE_TOKEN