language: node_js
node_js: lts/*
install: 
  - npm install -g firebase-tools
  - npm install
script: 
  - echo "script"
  - npm run build
deploy:
  provider: firebase
  token:
    secure: $FIREBASE_TOKEN